import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Result from "../components/Result";
import requests from "../utils/requests";

export default function Home({results}) {
  
  
	return (
		<div className="bg-[#06202A] text-gray-300">
			<Head>
				<title>Hulu</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* Header */}
			<Header />
			{/* nav */}
			<Navbar />
			{/* result */}
			<Result results={results}/>
		</div>
	);
}

export async function getServerSideProps(context) {
	const genre = context.query.genre;
	const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`).then((res)=>res.json());
  return {
    props:{
      results: request.results,
    }
  } ;
}
